name: Release beta

on: [ workflow_dispatch ]

jobs:
  beta_release:
    runs-on: ubuntu-latest
    steps:
    - name: prepare
      run:
        rm -rf ~/.cargo/registry
    - uses: actions/checkout@v3
    - name: cargo plugin cache
      id: cargo-plugin-cache
      uses: actions/cache@v2
      with:
        path: ~/.cargo/bin/
        key: ${{ runner.os }}-cargo-plugins
    - name: install cargo plugin
      if: steps.cargo-plugin-cache.outputs.cache-hit != 'true'
      run: cargo install cargo-release
    - name: Beta Release
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: |
        rm -rf ~/.cargo/registry
        git config --global user.email "ruimo.uno@gmail.com"
        git config --global user.name "Shisei Hanai"
        git status
        cargo release -vv beta --execute --no-confirm
